export default function suite() {
	// SHARE A UNSHARED LIST OWNED -> Success
	// SHARE A UNSHARED LIST NOT OWNED -> Fail
	// SHARE A GRANTED LIST OWNED -> Success
	// SHARE A GRANTED LIST NOT OWNED -> Fail
	// UNSHARE A UNSHARED LIST OWNED -> Success
	// UNSHARE A UNSHARED LIST NOT OWNED -> Fail
	// UNSHARE A GRANTED LIST OWNED -> Success
	// UNSHARE A GRANTED LIST NOT OWNED -> Fail
	// ADD A UNKNOWN LIST FROM SHARING CODE -> Success
	// ADD A ALREADY ADDED LIST FROM SHARING CODE -> Success
}
